version: '2'
services:
  elasticsearch:
   image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
   container_name: distracted_buck
   ports:
    - "9200:9200"
    - "9300:9300"
 kibana:
  image: docker.elastic.co/kibana/kibana:8.7.0
  container_name: Kibana
  ports:
    - "5601:5601"
  depends_on:
   - elasticsearch