version: '3'
services:
  server:
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    command: 
    - server
    - --node-taint
    - k3s/server=true:NoExecute
    tmpfs:
    - /run
    - /var/run
    privileged: true
    environment:
    - K3S_TOKEN=secret
    - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
    - K3S_KUBECONFIG_MODE=666
    volumes:
    - .:/output
    ports:
    - 6443:6443

  agent-1:
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    command:
    - agent
    - --node-taint
    - k3s/agent-1=true:NoExecute
    tmpfs:
    - /run
    - /var/run
    privileged: true
    environment:
    - K3S_URL=https://server:6443
    - K3S_TOKEN=secret

  agent-2:
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    command:
    - agent
    - --node-taint
    - k3s/agent-2=true:NoExecute
    tmpfs:
    - /run
    - /var/run
    privileged: true
    environment:
    - K3S_URL=https://server:6443
    - K3S_TOKEN=secret