version: '3.8'
services:
  setup:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
    user: "0"
    command: >
      bash -c '
        if [ x${ELASTIC_PASSWORD} == x ]; then
          echo "Set the ELASTIC_PASSWORD environment variable in the .env file";
          exit 1;
        elif [ x${KIBANA_PASSWORD} == x ]; then
          echo "Set the KIBANA_PASSWORD environment variable in the .env file";
          exit 1;
        fi;
        if [ ! -f config/certs/ca.zip ]; then
          echo "Creating CA";
          bin/elasticsearch-certutil ca --silent --pem -out config/certs/ca.zip;
          unzip config/certs/ca.zip -d config/certs;
        fi;
        if [ ! -f config/certs/certs.zip ]; then
          echo "Creating certs";
          echo -ne \
          "instances:\n"\
          "  - name: es01\n"\
          "    dns:\n"\
          "      - es01\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          "  - name: kibana\n"\
          "    dns:\n"\
          "      - kibana\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          > config/certs/instances.yml;
          bin/elasticsearch-certutil cert --silent --pem -out config/certs/certs.zip --in config/certs/instances.yml --ca-cert config/certs/ca/ca.crt --ca-key config/certs/ca/ca.key;
          unzip config/certs/certs.zip -d config/certs;
        fi;
        echo "Setting file permissions"
        chown -R root:root config/certs;
        find . -type d -exec chmod 750 \{\} \;;
        find . -type f -exec chmod 640 \{\} \;;
        echo "Waiting for Elasticsearch availability";
        until curl -s --cacert config/certs/ca/ca.crt https://es01:9200 | grep -q "missing authentication credentials"; do sleep 30; done;
        echo "Setting kibana_system password";
        until curl -s -X POST --cacert config/certs/ca/ca.crt -u "elastic:${ELASTIC_PASSWORD}" -H "Content-Type: application/json" https://es01:9200/_security/user/kibana_system/_password -d "{\"password\":\"${KIBANA_PASSWORD}\"}" | grep -q "^{}"; do sleep 10; done;
        echo "All done!";
      '
    healthcheck:
      test: ["CMD-SHELL", "[ -f config/certs/es01/es01.crt ]"]
      interval: 1s
      timeout: 5s
      retries: 120

  es-master-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: es-master-1
    environment:
      - node.name=es-master-1
      - cluster.name=my-cluster
      - discovery.seed_hosts=es-master-2,es-master-3
      - cluster.initial_master_nodes=es-master-1,es-master-2,es-master-3
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=${ES_JAVA_OPTS}"
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/esm01/esm01.key
      - xpack.security.http.ssl.certificate=certs/esm01/esm01.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/esm01/esm01.key
      - xpack.security.transport.ssl.certificate=certs/esm01/esm01.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=${LICENSE}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-master-1-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - es-net
    deploy:
      placement:
        constraints:
          - node.hostname==es-master-1

  es-master-2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: es-master-2
    environment:
      - node.name=es-master-2
      - cluster.name=my-cluster
      - discovery.seed_hosts=es-master-1,es-master-3
      - cluster.initial_master_nodes=es-master-1,es-master-2,es-master-3
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=${ES_JAVA_OPTS}"
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/esm02/esm02.key
      - xpack.security.http.ssl.certificate=certs/esm02/esm02.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/esm02/esm02.key
      - xpack.security.transport.ssl.certificate=certs/esm02/esm02.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=${LICENSE}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-master-2-data:/usr/share/elasticsearch/data
    networks:
      - es-net
    deploy:
      placement:
        constraints:
          - node.hostname==es-master-2

  es-master-3:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: es-master-3
    environment:
      - node.name=es-master-3
      - cluster.name=my-cluster
      - discovery.seed_hosts=es-master-1,es-master-2
      - cluster.initial_master_nodes=es-master-1,es-master-2,es-master-3
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=${ES_JAVA_OPTS}"
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/esm03/esm03.key
      - xpack.security.http.ssl.certificate=certs/esm03/esm03.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/esm03/esm03.key
      - xpack.security.transport.ssl.certificate=certs/esm03/esm03.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=${LICENSE}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-master-3-data:/usr/share/elasticsearch/data
    networks:
      - es-net
    deploy:
      placement:
        constraints:
          - node.hostname==es-master-3

  es-data-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: es-data-1
    environment:
      - node.name=es-data-1
      - cluster.name=my-cluster
      - discovery.seed_hosts=es-master-1,es-master-2,es-master-3
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=${ES_JAVA_OPTS}"
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/es01/es01.key
      - xpack.security.http.ssl.certificate=certs/es01/es01.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/es01/es01.key
      - xpack.security.transport.ssl.certificate=certs/es01/es01.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=${LICENSE}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data-1-data:/usr/share/elasticsearch/data
    networks:
      - es-net
    deploy:
      placement:
        constraints:
          - node.hostname==es-data-1

  es-data-2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: es-data-2
    environment:
      - node.name=es-data-2
      - cluster.name=my-cluster
      - discovery.seed_hosts=es-master-1,es-master-2,es-master-3
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=${ES_JAVA_OPTS}"
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/es02/es02.key
      - xpack.security.http.ssl.certificate=certs/es02/es02.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/es02/es02.key
      - xpack.security.transport.ssl.certificate=certs/es02/es02.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=${LICENSE}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data-2-data:/usr/share/elasticsearch/data
    networks:
      - es-net
    deploy:
      placement:
        constraints:
          - node.hostname==es-data-2

  es-data-3:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: es-data-3
    environment:
      - node.name=es-data-3
      - cluster.name=my-cluster
      - discovery.seed_hosts=es-master-1,es-master-2,es-master-3
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=${ES_JAVA_OPTS}"
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/es03/es03.key
      - xpack.security.http.ssl.certificate=certs/es03/es03.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/es03/es03.key
      - xpack.security.transport.ssl.certificate=certs/es03/es03.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=${LICENSE}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data-3-data:/usr/share/elasticsearch/data
    networks:
      - es-net
    deploy:
      placement:
        constraints:
          - node.hostname==es-data-3

  es-data-4:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: es-data-4
    environment:
      - node.name=es-data-4
      - cluster.name=my-cluster
      - discovery.seed_hosts=es-master-1,es-master-2,es-master-3
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=${ES_JAVA_OPTS}"
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/es04/es04.key
      - xpack.security.http.ssl.certificate=certs/es04/es04.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/es04/es04.key
      - xpack.security.transport.ssl.certificate=certs/es04/es04.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=${LICENSE}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data-4-data:/usr/share/elasticsearch/data
    networks:
      - es-net
    deploy:
      placement:
        constraints:
          - node.hostname==es-data-4

  es-data-5:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: es-data-5
    environment:
      - node.name=es-data-5
      - cluster.name=my-cluster
      - discovery.seed_hosts=es-master-1,es-master-2,es-master-3
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=${ES_JAVA_OPTS}"
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/es05/es05.key
      - xpack.security.http.ssl.certificate=certs/es05/es05.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/es05/es05.key
      - xpack.security.transport.ssl.certificate=certs/es05/es05.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=${LICENSE}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data-5-data:/usr/share/elasticsearch/data
    networks:
      - es-net
    deploy:
      placement:
        constraints:
          - node.hostname==es-data-5
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://es-master-1:9200
      - SERVERNAME=kibana
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
      - XPACK_SECURITY_ENCRYPTIONKEY=${ENCRYPTION_KEY}
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=${ENCRYPTION_KEY}
      - XPACK_REPORTING_ENCRYPTIONKEY=${ENCRYPTION_KEY}
    ports:
      - 5601:5601
    networks:
      - es-net
    depends_on:
      - es-master-1
      - es-master-2
      - es-master-3
      - es-data-1
      - es-data-2
      - es-data-3
      - es-data-4
      - es-data-5

volumes:
  certs:
    driver: local
  es-master-1:
    driver: local
  es-master-2:
    driver: local
  es-master-3:
    driver: local
  es-data-1:
    driver: local
  es-data-2:
    driver: local
  es-data-3:
    driver: local
  es-data-4:
    driver: local
  es-data-5:
    driver: local
  es-master-1-data:
  es-master-2-data:
  es-master-3-data:
  es-data-1-data:
  es-data-2-data:
  es-data-3-data:
  es-data-4-data:
  es-data-5-data:
  # Add more data node volumes as needed...

networks:
  es-net:
    external: false