version: '3.8'
services:
  es-master-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: es-master-1
    environment:
      - node.name=es-master-1
      - cluster.name=my-cluster
      - discovery.seed_hosts=es-master-2,es-master-3
      - cluster.initial_master_nodes=es-master-1,es-master-2,es-master-3
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=${ES_JAVA_OPTS}"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-master-1-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - es-net
    deploy:
      placement:
        constraints:
          - node.hostname==es-master-1

  es-master-2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: es-master-2
    environment:
      - node.name=es-master-2
      - cluster.name=my-cluster
      - discovery.seed_hosts=es-master-1,es-master-3
      - cluster.initial_master_nodes=es-master-1,es-master-2,es-master-3
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=${ES_JAVA_OPTS}"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-master-2-data:/usr/share/elasticsearch/data
    networks:
      - es-net
    deploy:
      placement:
        constraints:
          - node.hostname==es-master-2

  es-master-3:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: es-master-3
    environment:
      - node.name=es-master-3
      - cluster.name=my-cluster
      - discovery.seed_hosts=es-master-1,es-master-2
      - cluster.initial_master_nodes=es-master-1,es-master-2,es-master-3
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=${ES_JAVA_OPTS}"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-master-3-data:/usr/share/elasticsearch/data
    networks:
      - es-net
    deploy:
      placement:
        constraints:
          - node.hostname==es-master-3

  es-data-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: es-data-1
    environment:
      - node.name=es-data-1
      - cluster.name=my-cluster
      - discovery.seed_hosts=es-master-1,es-master-2,es-master-3
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=${ES_JAVA_OPTS}"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data-1-data:/usr/share/elasticsearch/data
    networks:
      - es-net
    deploy:
      placement:
        constraints:
          - node.hostname==es-data-1

  es-data-2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: es-data-2
    environment:
      - node.name=es-data-2
      - cluster.name=my-cluster
      - discovery.seed_hosts=es-master-1,es-master-2,es-master-3
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=${ES_JAVA_OPTS}"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data-2-data:/usr/share/elasticsearch/data
    networks:
      - es-net
    deploy:
      placement:
        constraints:
          - node.hostname==es-data-2

  es-data-3:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: es-data-3
    environment:
      - node.name=es-data-3
      - cluster.name=my-cluster
      - discovery.seed_hosts=es-master-1,es-master-2,es-master-3
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=${ES_JAVA_OPTS}"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data-3-data:/usr/share/elasticsearch/data
    networks:
      - es-net
    deploy:
      placement:
        constraints:
          - node.hostname==es-data-3

  es-data-4:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: es-data-4
    environment:
      - node.name=es-data-4
      - cluster.name=my-cluster
      - discovery.seed_hosts=es-master-1,es-master-2,es-master-3
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=${ES_JAVA_OPTS}"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data-4-data:/usr/share/elasticsearch/data
    networks:
      - es-net
    deploy:
      placement:
        constraints:
          - node.hostname==es-data-4

  es-data-5:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: es-data-5
    environment:
      - node.name=es-data-5
      - cluster.name=my-cluster
      - discovery.seed_hosts=es-master-1,es-master-2,es-master-3
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=${ES_JAVA_OPTS}"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data-5-data:/usr/share/elasticsearch/data
    networks:
      - es-net
    deploy:
      placement:
        constraints:
          - node.hostname==es-data-5
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://es-master-1:9200
    ports:
      - 5601:5601
    networks:
      - es-net
    depends_on:
      - es-master-1
      - es-master-2
      - es-master-3
      - es-data-1
      - es-data-2
      - es-data-3
      - es-data-4
      - es-data-5

volumes:
  es-master-1-data:
  es-master-2-data:
  es-master-3-data:
  es-data-1-data:
  es-data-2-data:
  es-data-3-data:
  es-data-4-data:
  es-data-5-data:
  # Add more data node volumes as needed...

networks:
  es-net:
